# ─────────────────────────────────────────────────────────────
# scripts/install-to-repo.ps1
# 把当前仓库的 .github/workflows/auto-add-to-project.yml 部署到任意其他仓库
# 同时设置 PROJECT_NUMBER 变量 + Actions 写权限 + 触发首次 push 让 GitHub 注册 workflow
#
# 用法：
#   pwsh scripts/install-to-repo.ps1 -TargetRepo "laiyinyizao007/other-repo"
#   pwsh scripts/install-to-repo.ps1 -TargetRepo "laiyinyizao007/foo" -ProjectNumber 2
#
# 前置条件（在目标仓库需手动完成，脚本不会触碰 secrets）：
#   1. PAT（repo + project scope）已添加到目标仓库 Secret: PROJECT_TOKEN
#   2. 已 `gh auth login`，或已设置 GH_TOKEN 环境变量
# ─────────────────────────────────────────────────────────────

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$TargetRepo,

    [string]$ProjectNumber = '1'
)

$ErrorActionPreference = 'Stop'

# 1) 读取源仓库的 workflow 内容
$SOURCE_REPO = 'laiyinyizao007/my-project-management'
$WORKFLOW_PATH = '.github/workflows/auto-add-to-project.yml'

Write-Host "📦 读取源 workflow..." -ForegroundColor Cyan
$sourceContent = gh api "repos/$SOURCE_REPO/contents/$WORKFLOW_PATH" `
    --jq '.content' | ForEach-Object { [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($_)) }

if (-not $sourceContent) {
    throw "❌ 无法读取源文件 $WORKFLOW_PATH"
}

Write-Host "   ✅ 已加载 $(($sourceContent -split "`n").Count) 行 workflow 内容" -ForegroundColor Green
Write-Host ""

# 2) 把 workflow 推送到目标仓库
Write-Host "🚀 部署到 $TargetRepo ..." -ForegroundColor Yellow

# 检查目标仓库是否有同名 workflow
$existing = gh api "repos/$TargetRepo/contents/$WORKFLOW_PATH" 2>$null
if ($LASTEXITCODE -eq 0 -and $existing) {
    $sha = $existing | ConvertFrom-Json | Select-Object -ExpandProperty sha
    Write-Host "   🔄 工作流已存在，将更新（SHA: $($sha.Substring(0,7))）" -ForegroundColor DarkYellow
    $body = @{
        message = "chore: 部署 auto-add-to-project workflow（同步自 $SOURCE_REPO）"
        content = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($sourceContent))
        sha     = $sha
    } | ConvertTo-Json -Depth 10
    $body | gh api "repos/$TargetRepo/contents/$WORKFLOW_PATH" --method PUT --input - | Out-Null
    Write-Host "   ✅ 工作流已更新" -ForegroundColor Green
} else {
    $body = @{
        message = "chore: 部署 auto-add-to-project workflow（同步自 $SOURCE_REPO）"
        content = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($sourceContent))
    } | ConvertTo-Json -Depth 10
    $body | gh api "repos/$TargetRepo/contents/$WORKFLOW_PATH" --method PUT --input - | Out-Null
    Write-Host "   ✅ 工作流已创建" -ForegroundColor Green
}

Write-Host ""

# 3) 设置目标仓库的 PROJECT_NUMBER 变量
Write-Host "🔧 [2/4] 设置 $TargetRepo 的 PROJECT_NUMBER=$ProjectNumber ..." -ForegroundColor Yellow

gh variable set PROJECT_NUMBER --body $ProjectNumber --repo $TargetRepo
Write-Host "   ✅ 仓库变量已设置" -ForegroundColor Green
Write-Host ""

# 4) 修目标仓库的 Actions 权限为 write（避免新增的仓库再失败）
Write-Host "🔐 [3/4] 设置 $TargetRepo 的 Actions workflow 权限为 write ..." -ForegroundColor Yellow

$permBody = @{
    default_workflow_permissions     = 'write'
    can_approve_pull_request_reviews = $false
} | ConvertTo-Json

$permBody | gh api "repos/$TargetRepo/actions/permissions/workflow" --method PUT --input - | Out-Null
Write-Host "   ✅ Actions 权限已更新为 write" -ForegroundColor Green
Write-Host ""

# 5) 触发空 push 让 GitHub 注册 workflow（首次部署必须）
Write-Host "🚀 [4/4] 触发空 push 让 GitHub 注册 workflow..." -ForegroundColor Yellow

$keepContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("# Generated by install-to-repo.ps1`n"))

# 检查 .github/.keep 是否已存在
$existingKeep = gh api "repos/$TargetRepo/contents/.github/.keep" 2>$null
if ($LASTEXITCODE -eq 0 -and $existingKeep) {
    Write-Host "   ⏭️  .github/.keep 已存在，跳过空 push" -ForegroundColor DarkYellow
} else {
    $keepBody = @{
        message = "chore: 初始化 .github 目录（触发 workflow 注册）"
        content = $keepContent
    } | ConvertTo-Json

    $keepBody | gh api "repos/$TargetRepo/contents/.github/.keep" --method PUT --input - | Out-Null
    Write-Host "   ✅ 已创建 .github/.keep（这次 push 会触发 workflow 注册）" -ForegroundColor Green
}

Write-Host ""

Write-Host "🎉 全部完成！$TargetRepo 已配置为自动将 Issue 加入 Project #${ProjectNumber}。" -ForegroundColor Cyan
Write-Host ""
Write-Host "📌 下一步：" -ForegroundColor Yellow
Write-Host "   1. 等待 1-2 分钟让 GitHub 完成 workflow 注册（首次部署必须）"
Write-Host "   2. 在 $TargetRepo 中创建任意 Issue，验证自动入看板"
Write-Host "   3. 确认 Project 看板中能看到新 Issue"
Write-Host ""
Write-Host "💡 提示：如 Issue 创建后未自动入看板，可去 Settings → Actions 查看 workflow 是否报错。" -ForegroundColor DarkCyan
Write-Host ""